# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebef2a8354fad02053e752dad70d08edaf5aa977cf2729000ec675b631d6858a3d9eb39df3dbc17f1fe09aa1a1f692a07f4c33df674e5eac842f1e7152615730

test:
  secret_key_base: a9ef10dbf92016533eb3dc289d852982f4a2c35cc299c124045d4a6393d9e097a27b3a2ddc99bebddcafc98d1670de916fa6595ca59913bd4950b4dd53b66802

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
